### ISSUE TITLE
Publish a minified build?

### ISSUE THREAD

**Issue by radiovisual** [JayKid/bookmark-focus-highlight#3]
I just shared this bookmark, but sharing the repo means sharing the project, which requires a build. For users who just want the fruit of your labour, it would be nice to be able to point to the bookmark so they can copy-paste the minified JavaScript.

_What'chu think, mang?_

**Comment by JayKid** [comment]
I thought about it already 🙈  because I had to do the same several times...

I'm waiting for the merge of https://github.com/JayKid/bookmark-focus-highlight/pull/2 to do it : )

**Comment by JayKid** [comment]
@radiovisual Should be fine now : ) You can find the built code [here](https://github.com/JayKid/bookmark-focus-highlight/blob/master/dist/main.js).

**Comment by radiovisual** [comment]
*NOICE!* Thanks!
